#!/usr/bin/env python3
"""
Check for broken internal links in markdown files.
Analyzes both markdown-style and HTML-style links.
"""

import os
import re
from pathlib import Path
from collections import defaultdict
from urllib.parse import urlparse, unquote

INTERNAL_HOSTS = {'joshuapsteele.com', 'www.joshuapsteele.com', 'joshuapsteele.github.io'}

def split_front_matter(text):
    """Return the YAML front matter block, or an empty string if absent."""
    match = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n", text, flags=re.DOTALL)
    return match.group(1) if match else ""

def parse_inline_list(raw):
    """Parse a simple YAML inline list like [one, "two words"]."""
    inner = raw.strip()[1:-1]
    items = []
    buf = ""
    in_quote = False
    quote = ""

    for ch in inner:
        if ch in {"'", '"'}:
            if in_quote and ch == quote:
                in_quote = False
            elif not in_quote:
                in_quote = True
                quote = ch
            buf += ch
            continue
        if ch == "," and not in_quote:
            item = buf.strip().strip("'\"")
            if item:
                items.append(item)
            buf = ""
            continue
        buf += ch

    item = buf.strip().strip("'\"")
    if item:
        items.append(item)
    return items

def parse_frontmatter_value(fm, key):
    """Parse a scalar, inline list, or block list front matter field."""
    inline = re.search(rf"(?m)^{re.escape(key)}:\s*(.*?)\s*$", fm)
    if not inline:
        return None

    value = inline.group(1).strip()
    if value.startswith("[") and value.endswith("]"):
        return parse_inline_list(value)
    if value:
        return value.strip("'\"")

    items = []
    after = fm[inline.end():]
    for line in after.splitlines():
        match = re.match(r"^\s*-\s+(.*?)\s*$", line)
        if not match:
            break
        items.append(match.group(1).strip().strip("'\""))
    return items

def add_url_variants(valid_urls, url):
    """Add URL variants with and without trailing slashes."""
    if not url:
        return
    valid_urls.add(url)
    valid_urls.add(url.rstrip('/'))
    if not url.endswith('/'):
        valid_urls.add(url + '/')

def slugify_taxonomy(term):
    return re.sub(r'[^a-z0-9-]', '', re.sub(r'[\s_]+', '-', term.lower()))

def get_all_urls_and_paths(content_dir):
    """Build a map of all valid URLs and file paths in the site"""
    valid_urls = set()
    valid_paths = set()

    for root, dirs, files in os.walk(content_dir):
        for filename in files:
            if filename.endswith('.md'):
                filepath = os.path.join(root, filename)

                try:
                    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                        fm = split_front_matter(f.read())

                    # Add the file's URL if it has one
                    url = parse_frontmatter_value(fm, 'url')
                    if isinstance(url, str):
                        add_url_variants(valid_urls, url.strip())
                    else:
                        rel_path = os.path.relpath(filepath, content_dir)
                        stem = Path(rel_path).with_suffix('').as_posix()
                        if stem.startswith('pages/'):
                            add_url_variants(valid_urls, '/' + stem.removeprefix('pages/') + '/')
                        elif stem.startswith('notes/'):
                            add_url_variants(valid_urls, '/' + stem + '/')
                        elif stem.startswith('blog/'):
                            add_url_variants(valid_urls, '/' + stem.removeprefix('blog/') + '/')
                            add_url_variants(valid_urls, '/' + stem + '/')
                        else:
                            add_url_variants(valid_urls, '/' + stem + '/')

                    # Add aliases
                    aliases = parse_frontmatter_value(fm, 'aliases')
                    if aliases:
                        if isinstance(aliases, str):
                            aliases = [aliases]
                        for alias in aliases:
                            add_url_variants(valid_urls, alias.strip())

                    # Add taxonomy URLs generated by Hugo.
                    for key, base_path in (('tags', '/tags/'), ('categories', '/categories/')):
                        terms = parse_frontmatter_value(fm, key)
                        if isinstance(terms, str):
                            terms = [terms]
                        if terms:
                            for term in terms:
                                slug = slugify_taxonomy(term)
                                if slug:
                                    add_url_variants(valid_urls, base_path + slug + '/')

                    # Add the relative file path
                    rel_path = os.path.relpath(filepath, content_dir)
                    valid_paths.add(rel_path)

                except Exception as e:
                    pass

    static_dir = Path('static')
    if static_dir.exists():
        for static_file in static_dir.rglob('*'):
            if static_file.is_file():
                add_url_variants(valid_urls, '/' + static_file.relative_to(static_dir).as_posix())

    return valid_urls, valid_paths

def extract_links(content):
    """Extract all markdown and HTML links from content"""
    links = []

    # Markdown links: [text](url)
    md_pattern = r'\[([^\]]+)\]\(([^)]+)\)'
    for match in re.finditer(md_pattern, content):
        text = match.group(1)
        url = match.group(2)
        links.append({'type': 'markdown', 'text': text, 'url': url})

    # HTML links: <a href="url">
    html_pattern = r'<a\s+(?:[^>]*?\s+)?href=["\']([^"\']+)["\']'
    for match in re.finditer(html_pattern, content, re.IGNORECASE):
        url = match.group(1)
        links.append({'type': 'html', 'text': '', 'url': url})

    return links

def is_internal_link(url):
    """Check if a URL is an internal link"""
    # Skip external URLs
    if url.startswith(('http://', 'https://', '//')):
        parsed = urlparse(url)
        # Only consider it internal if it's explicitly joshuapsteele.com
        if parsed.netloc in INTERNAL_HOSTS:
            return True
        return False

    # Skip anchors, mailto, and other special protocols
    if url.startswith(('#', 'mailto:', 'tel:', 'javascript:')):
        return False

    # Everything else starting with / or relative is internal
    if url.startswith('/') or not url.startswith(('http', '//')):
        return True

    return False

def normalize_url(url):
    """Normalize a URL for comparison"""
    parsed = urlparse(url)
    if parsed.scheme in {'http', 'https'} and parsed.netloc in INTERNAL_HOSTS:
        url = parsed.path
    else:
        url = url.split('?')[0].split('#')[0]
    url = unquote(url)
    return url.rstrip('/') or '/'

def check_internal_links(content_dir):
    """Check all internal links in markdown files"""
    results = {
        'total_files': 0,
        'total_links': 0,
        'internal_links': 0,
        'broken_links': defaultdict(list),
        'working_links': 0,
        'files_with_broken_links': set(),
    }

    print("Building site URL map...")
    valid_urls, valid_paths = get_all_urls_and_paths(content_dir)
    print(f"Found {len(valid_urls)} valid URLs and {len(valid_paths)} valid paths")

    print("\nChecking internal links...")

    for root, dirs, files in os.walk(content_dir):
        for filename in files:
            if filename.endswith('.md'):
                filepath = os.path.join(root, filename)
                results['total_files'] += 1

                try:
                    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                        content = f.read()

                    links = extract_links(content)

                    for link in links:
                        url = link['url']
                        results['total_links'] += 1

                        if not is_internal_link(url):
                            continue

                        results['internal_links'] += 1

                        # Normalize the URL
                        normalized = normalize_url(url)

                        # Check if it exists
                        is_valid = False

                        # Check against valid URLs
                        if normalized in valid_urls or (normalized + '/') in valid_urls:
                            is_valid = True

                        # Check for relative paths
                        if not is_valid and not url.startswith('/'):
                            # Try to resolve relative path
                            current_dir = os.path.dirname(filepath)
                            target_path = os.path.normpath(os.path.join(current_dir, url))
                            if os.path.exists(target_path):
                                is_valid = True

                        # Check for common patterns
                        if not is_valid:
                            # Remove leading slash for checking
                            check_url = normalized.lstrip('/')

                            # Check if it's a valid file reference
                            possible_paths = [
                                f"blog/{check_url}.md",
                                f"pages/{check_url}.md",
                                f"{check_url}.md",
                                check_url,
                            ]

                            for path in possible_paths:
                                full_path = os.path.join(content_dir, path)
                                if os.path.exists(full_path):
                                    is_valid = True
                                    break

                        if is_valid:
                            results['working_links'] += 1
                        else:
                            rel_filepath = os.path.relpath(filepath, content_dir)
                            results['broken_links'][rel_filepath].append({
                                'type': link['type'],
                                'text': link['text'],
                                'url': url,
                                'normalized': normalized
                            })
                            results['files_with_broken_links'].add(rel_filepath)

                except Exception as e:
                    print(f"Error processing {filepath}: {e}")

    return results

def main():
    print("=" * 80)
    print("INTERNAL LINK CHECK")
    print("=" * 80)
    print()

    results = check_internal_links('content/')

    # Print summary
    print("\n" + "=" * 80)
    print("SUMMARY")
    print("=" * 80)
    print(f"\n📊 Files Analyzed: {results['total_files']}")
    print(f"🔗 Total Links Found: {results['total_links']}")
    print(f"🏠 Internal Links: {results['internal_links']}")
    print(f"✅ Working Internal Links: {results['working_links']}")
    print(f"❌ Broken Internal Links: {sum(len(v) for v in results['broken_links'].values())}")
    print(f"📄 Files with Broken Links: {len(results['files_with_broken_links'])}")

    # Save detailed results
    import json
    output_path = Path('scripts/data/audit-internal-links.json')
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open('w') as f:
        # Convert set to list for JSON serialization
        output = dict(results)
        output['files_with_broken_links'] = sorted(list(results['files_with_broken_links']))
        json.dump(output, f, indent=2, default=str)

    print(f"\n✅ Detailed results saved to: {output_path}")

    # Print broken links
    if results['broken_links']:
        print("\n" + "=" * 80)
        print("BROKEN LINKS BY FILE")
        print("=" * 80)

        for filepath in sorted(results['broken_links'].keys()):
            print(f"\n📄 {filepath}")
            for link in results['broken_links'][filepath]:
                print(f"   ❌ [{link['text']}]({link['url']})")
                if link['normalized'] != link['url']:
                    print(f"      (normalized: {link['normalized']})")

    print("\n" + "=" * 80)

if __name__ == "__main__":
    main()
