name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # Trigger the workflow when you push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'  # You can pin a specific Hugo version here

      - name: Build site
        run: hugo --gc --minify  # No `-d docs`, default build to `public/`

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Deploy from the `public` folder to the root of `gh-pages`
